Global:
 CreateExplosions: true
 Updates:
  ShowPercentageOnUpdate: true
  CheckOnStartup: true
  CheckDelay: 300
 Logging:
  Enabled: false
  MinimumMsForLog: 1000
  LogEvents: true
  LogItems: true
  LogEnchantments: true
 Enchantments:
  CEnchantmentColor: DARK_RED;ITALIC
  CEnchantmentTable: true
  CEnchantingProbability: 10
  MaximumCustomEnchantments: 1000
  UseCustomEnchantmentProbability: false
  RequirePermissions: true
  RepeatPotionEffects: true
  RepeatDelay: 1000
Enchantments: